Repository bleykauf/aisim, pull requests merged in 2020-06, with the labels that each got.

#22 Build documentation on readthedocs.org
  .readthedocs.yml
  docs/conf.py
  docs/requirements.txt
Labels: documentation

#26 Update documentation
  README.rst
Labels: documentation

#34 Implement tests and CI
  .travis.yml
  aisim/convert.py
  aisim/tests/convert_test.py
  tox.ini
Labels: enhancement

#38 Getting travis to work again
  .travis.yml
  README.md
  tests/convert_test.py
  tox.ini
Labels: bug

#36 Unify the propagation methods into a class
  aisim/prop.py
  docs/examples/basic-usage.ipynb
  docs/examples/rabi-oscillations.ipynb
  docs/examples/rabi-oscillations.png
  docs/examples/wavefront-aberrations.ipynb
Labels: enhancement

#37 state_vectors to state_kets
  aisim/atoms.py
  aisim/prop.py
Labels: enhancement

#41 Adding contributions guide and enfore it
  aisim/__init__.py
  aisim/atoms.py
  aisim/beam.py
  aisim/convert.py
  aisim/det.py
  aisim/prop.py
  aisim/sims.py
  docs/CONTRIBUTING.rst
  docs/dev.rst
  setup.cfg
  tests/.gitkeep
  tests/convert_test.py
Labels: code style, documentation, enhancement

#40 Tests for aisim's modules
  aisim/__init__.py
  aisim/atoms.py
  aisim/beam.py
  aisim/convert.py
  aisim/sims.py
  docs/examples/basic-usage.ipynb
  docs/examples/data/wf_grav_data.csv
  docs/examples/data/wf_window.txt
  docs/examples/data/wf_window5.txt
  docs/examples/rabi-oscillations.ipynb
  docs/examples/rabi-oscillations.png
  docs/examples/wavefront-aberrations.ipynb
  docs/usage.rst
  tests/atoms_test.py
  tests/beam_test.py
  tests/convert_test.py
  tests/prop_test.py
  tests/wf_test.py
Labels: enhancement
